name: network_kit
description: A lightweight, dependency-free wrapper around Dio for unified error handling and offline support.
version: 0.0.1
repository: https://github.com/yourusername/network_kit
issue_tracker: https://github.com/yourusername/network_kit/issues
publish_to: 'none' # Temporary until ready

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  connectivity_plus: ^6.0.0
  shared_preferences: ^2.3.0
  meta: ^1.11.0

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.0
