name: network_kit
description: A high-performance, resilient networking engine for Flutter. Features background JSON parsing, automated offline queuing, and order-preserving synchronization.
version: 0.1.0
homepage: https://github.com/mehdihassan93/network_kit
repository: https://github.com/mehdihassan93/network_kit
issue_tracker: https://github.com/mehdihassan93/network_kit/issues
topics:
  - networking
  - dio
  - offline
  - sync
  - json-parsing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  connectivity_plus: ^6.0.0
  shared_preferences: ^2.3.0
  meta: ^1.11.0

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.0

# No assets needed in code
